name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        id: maven_build

      - name: Extract some value
        run: echo "VARIABLE_NAME=${{ steps.step_id.outputs.value }}" >> $GITHUB_ENV

      - name: Use MY_VARIABLE
        run: echo "Value of MY_VARIABLE is $MY_VARIABLE"

      - name: Update dependency graph
        if: success() # Only run this step if all previous steps were successful
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
